version: '{build}'
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
install:
# Install repo specific stuff here
before_build:
# Display .NET Core version
- cmd: dotnet --version
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\Build.ps1
test: off
artifacts:
- path: .\libraries\Bot.Builder.Elasticsearch.Storage\artifacts\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  server: https://www.myget.org/F/pratikpanda-ci/api/v2/package
  api_key:
    secure: k9Fgm7+DHC2pNKjg+DDy5D147PFw5y0IFc5GnXxLgmfm7Em2BOLQLYkdeEIaUBOm
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: sk+mDXwakNPm1lLFerBQ9Svcb81GI8u+/9dAjt7nRzN9v/qDr9iF0RgztiD+UfsI
  on:
    branch: master
    appveyor_repo_tag: true