version: '{build}'
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
install:
# Install repo specific stuff here
before_build:
# Display .NET Core version
- cmd: dotnet --version
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\Build.ps1
test: off
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: sk+mDXwakNPm1lLFerBQ9Svcb81GI8u+/9dAjt7nRzN9v/qDr9iF0RgztiD+UfsI
  on:
    branch: master
    appveyor_repo_tag: true